name: Deploy to S3
on:
    pull_request:
      branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: "20"
            - name: Install Dependencies
              run: npm i
            - name: Build App
              run: npm run build
    deploy:
        runs-on: ubuntu-22.04
        steps:
            - name: Configure AWS
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            - run: aws s3 sync ./out s3://mchewittwedding.com